
#+TITLE: Seeds of the New World

* TODO Somewhere mention how democracy is a failed model
Lobbying and all that. Hijacked by the arsehole of Trump. Freedom of press down (Trump) to unprecedented times.

* TODO Tourism a global problem

https://www.bbc.com/travel/article/20240522-the-worlds-revolt-against-bad-tourists

*** TODO Add living rapidly decreasing living standards across the globe
In the intro
The US goes down since the 70s.

* Emerging alternatives
# BRICS+ etc, initiatives already in progress. These will be TEMPORARY and transitionary (make that clear), not full Phoenix yet.

* Prognosis
# ??? Internet
** USA
** EU
** MX
# CDMX water collapse
# Narco system after drug trade sinks

** BRICS+

* New hope

  Here's the thing: many people are already living in the new Earth. It's been such a quiet shift, many never noticed it. Yet, the wise don't need to shout and the truly powerful don't need to hit. More and more people joined the silent non-movement and started to grow their own produce, use eco-friendly technology and mainly -- and very much in line with the sleeping phoenix -- they took the responsibility for themselves.

  https://www.bbc.com/travel/article/20250425-the-us-island-where-cars-are-banned

** Permaculture

  https://www.resilience.org/stories/2020-05-15/fruit-trenches-cultivating-subtropical-plants-in-freezing-temperatures/

** New non-tech

  As soon as we fall in place, new doors will open.

  We are stuck in the old, that we are oblivious to the new. We have our gaze fixed on the demolition site that we do not see the cherry trees flourishing above it.

  https://www.bbc.com/future/article/20240419-the-worms-that-eat-through-plastic

** What I'm doing

  I want to add my example simply to show what's manageable for a single normal person to do. Because it's not really about what could theoretically be done (after spending 20 years studying it), but what's doable, manageable and realistic to learn and build within few short years.

  First, I identified an area of interest: a South-facing slope between Cuernavaca and Mexico City with very temperate climate (due to thermal dynamics on the slope, hot air raises along the slope during the day and due to decent forest cover in the area that maintains the temperature stable) and even more importantly -- abundant rainfall.

  I visited the area. My goal was to search on the lower parts of the slope, but since the bus stops in a town on the upper side, I went there. I immediately loved it -- I knew it was the right place to search. We asked a random person whether they know about lands for sale -- and he happened to have a family member that did. They showed us various lands, one of each was absolutely perfect (and dirt cheap) for us. Both me and my wife immediately recognised this is the right land for us.

  It will allow us to live only o....
